import { db } from '@/db';
import { marbleInventory } from '@/db/schema';

async function main() {
    const sampleInventory = [
        // Carrara Marble (5 items)
        {
            marbleType: 'Carrara',
            size: '60x60 cm',
            quality: 'Premium',
            quantity: 45,
            pricePerUnit: 12500,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            marbleType: 'Carrara',
            size: '80x80 cm',
            quality: 'Standard',
            quantity: 78,
            pricePerUnit: 6800,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            marbleType: 'Carrara',
            size: '120x60 cm',
            quality: 'Premium',
            quantity: 8,
            pricePerUnit: 14200,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            marbleType: 'Carrara',
            size: '30x30 cm',
            quality: 'Commercial',
            quantity: 185,
            pricePerUnit: 3200,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-28').toISOString(),
        },
        {
            marbleType: 'Carrara',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 15,
            pricePerUnit: 15000,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-01').toISOString(),
        },

        // Nero Marquina (5 items)
        {
            marbleType: 'Nero Marquina',
            size: '60x60 cm',
            quality: 'Premium',
            quantity: 32,
            pricePerUnit: 13800,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            marbleType: 'Nero Marquina',
            size: '80x80 cm',
            quality: 'Standard',
            quantity: 52,
            pricePerUnit: 7200,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            marbleType: 'Nero Marquina',
            size: '120x60 cm',
            quality: 'Standard',
            quantity: 28,
            pricePerUnit: 6500,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            marbleType: 'Nero Marquina',
            size: '30x30 cm',
            quality: 'Commercial',
            quantity: 220,
            pricePerUnit: 3800,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            marbleType: 'Nero Marquina',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 6,
            pricePerUnit: 14500,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-05').toISOString(),
        },

        // Calacatta (5 items)
        {
            marbleType: 'Calacatta',
            size: '60x60 cm',
            quality: 'Premium',
            quantity: 25,
            pricePerUnit: 14800,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            marbleType: 'Calacatta',
            size: '80x80 cm',
            quality: 'Premium',
            quantity: 18,
            pricePerUnit: 13500,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            marbleType: 'Calacatta',
            size: '120x60 cm',
            quality: 'Standard',
            quantity: 42,
            pricePerUnit: 7800,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            marbleType: 'Calacatta',
            size: '30x30 cm',
            quality: 'Standard',
            quantity: 95,
            pricePerUnit: 5200,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            marbleType: 'Calacatta',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 9,
            pricePerUnit: 15000,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-08').toISOString(),
        },

        // Emperador Dark (5 items)
        {
            marbleType: 'Emperador Dark',
            size: '60x60 cm',
            quality: 'Standard',
            quantity: 65,
            pricePerUnit: 5800,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-18').toISOString(),
        },
        {
            marbleType: 'Emperador Dark',
            size: '80x80 cm',
            quality: 'Premium',
            quantity: 38,
            pricePerUnit: 11200,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            marbleType: 'Emperador Dark',
            size: '120x60 cm',
            quality: 'Standard',
            quantity: 7,
            pricePerUnit: 6200,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            marbleType: 'Emperador Dark',
            size: '30x30 cm',
            quality: 'Commercial',
            quantity: 150,
            pricePerUnit: 2800,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-22').toISOString(),
        },
        {
            marbleType: 'Emperador Dark',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 12,
            pricePerUnit: 12800,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-03').toISOString(),
        },

        // Statuario (5 items)
        {
            marbleType: 'Statuario',
            size: '60x60 cm',
            quality: 'Premium',
            quantity: 28,
            pricePerUnit: 13200,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-16').toISOString(),
        },
        {
            marbleType: 'Statuario',
            size: '80x80 cm',
            quality: 'Standard',
            quantity: 58,
            pricePerUnit: 7500,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            marbleType: 'Statuario',
            size: '120x60 cm',
            quality: 'Standard',
            quantity: 35,
            pricePerUnit: 6800,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            marbleType: 'Statuario',
            size: '30x30 cm',
            quality: 'Commercial',
            quantity: 175,
            pricePerUnit: 3500,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-14').toISOString(),
        },
        {
            marbleType: 'Statuario',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 5,
            pricePerUnit: 14800,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-10').toISOString(),
        },

        // Crema Marfil (5 items)
        {
            marbleType: 'Crema Marfil',
            size: '60x60 cm',
            quality: 'Standard',
            quantity: 72,
            pricePerUnit: 5500,
            location: 'Warehouse-A',
            createdAt: new Date('2024-10-19').toISOString(),
        },
        {
            marbleType: 'Crema Marfil',
            size: '80x80 cm',
            quality: 'Premium',
            quantity: 40,
            pricePerUnit: 10800,
            location: 'Warehouse-B',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            marbleType: 'Crema Marfil',
            size: '120x60 cm',
            quality: 'Standard',
            quantity: 48,
            pricePerUnit: 5800,
            location: 'Storage-Zone-1',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            marbleType: 'Crema Marfil',
            size: '30x30 cm',
            quality: 'Commercial',
            quantity: 250,
            pricePerUnit: 2500,
            location: 'Warehouse-C',
            createdAt: new Date('2024-10-11').toISOString(),
        },
        {
            marbleType: 'Crema Marfil',
            size: '240x120 cm',
            quality: 'Premium',
            quantity: 11,
            pricePerUnit: 12200,
            location: 'Storage-Zone-2',
            createdAt: new Date('2024-12-07').toISOString(),
        },
    ];

    await db.insert(marbleInventory).values(sampleInventory);
    
    console.log('✅ Marble inventory seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});