import { db } from '@/db';
import { productionOrders } from '@/db/schema';

async function main() {
    const sampleProductionOrders = [
        {
            orderId: 'PO-2024-001',
            stage: 'Cutting',
            progress: 45,
            assignedEmployee: 'John Smith',
            startDate: new Date('2024-01-05').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-04').toISOString(),
        },
        {
            orderId: 'PO-2024-002',
            stage: 'Polishing',
            progress: 65,
            assignedEmployee: 'Maria Garcia',
            startDate: new Date('2024-01-08').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-07').toISOString(),
        },
        {
            orderId: 'PO-2024-003',
            stage: 'Packaging',
            progress: 90,
            assignedEmployee: 'Ahmed Hassan',
            startDate: new Date('2024-01-10').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-09').toISOString(),
        },
        {
            orderId: 'PO-2024-004',
            stage: 'Delivery',
            progress: 100,
            assignedEmployee: 'David Chen',
            startDate: new Date('2024-01-12').toISOString(),
            endDate: new Date('2024-01-25').toISOString(),
            status: 'Completed',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            orderId: 'PO-2024-005',
            stage: 'Cutting',
            progress: 25,
            assignedEmployee: 'Sarah Johnson',
            startDate: new Date('2024-01-15').toISOString(),
            endDate: null,
            status: 'On Hold',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            orderId: 'PO-2024-006',
            stage: 'Polishing',
            progress: 55,
            assignedEmployee: 'Roberto Martinez',
            startDate: new Date('2024-01-18').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            orderId: 'PO-2024-007',
            stage: 'Packaging',
            progress: 75,
            assignedEmployee: 'Kim Lee',
            startDate: new Date('2024-01-20').toISOString(),
            endDate: null,
            status: 'Delayed',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            orderId: 'PO-2024-008',
            stage: 'Delivery',
            progress: 85,
            assignedEmployee: 'James Wilson',
            startDate: new Date('2024-01-22').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            orderId: 'PO-2024-009',
            stage: 'Cutting',
            progress: 35,
            assignedEmployee: null,
            startDate: new Date('2024-01-25').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            orderId: 'PO-2024-010',
            stage: 'Polishing',
            progress: 70,
            assignedEmployee: 'Anna Kowalski',
            startDate: new Date('2024-01-28').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-27').toISOString(),
        },
        {
            orderId: 'PO-2024-011',
            stage: 'Packaging',
            progress: 95,
            assignedEmployee: 'Mohammed Ali',
            startDate: new Date('2024-02-01').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-01-31').toISOString(),
        },
        {
            orderId: 'PO-2024-012',
            stage: 'Delivery',
            progress: 100,
            assignedEmployee: 'Lisa Anderson',
            startDate: new Date('2024-02-03').toISOString(),
            endDate: new Date('2024-02-18').toISOString(),
            status: 'Completed',
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            orderId: 'PO-2024-013',
            stage: 'Cutting',
            progress: 50,
            assignedEmployee: 'Carlos Rodriguez',
            startDate: new Date('2024-02-05').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-04').toISOString(),
        },
        {
            orderId: 'PO-2024-014',
            stage: 'Polishing',
            progress: 40,
            assignedEmployee: 'Yuki Tanaka',
            startDate: new Date('2024-02-08').toISOString(),
            endDate: null,
            status: 'Delayed',
            createdAt: new Date('2024-02-07').toISOString(),
        },
        {
            orderId: 'PO-2024-015',
            stage: 'Packaging',
            progress: 80,
            assignedEmployee: 'Michael Brown',
            startDate: new Date('2024-02-10').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-09').toISOString(),
        },
        {
            orderId: 'PO-2024-016',
            stage: 'Delivery',
            progress: 95,
            assignedEmployee: 'Elena Popov',
            startDate: new Date('2024-02-12').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-11').toISOString(),
        },
        {
            orderId: 'PO-2024-017',
            stage: 'Cutting',
            progress: 15,
            assignedEmployee: 'Hassan Ibrahim',
            startDate: new Date('2024-02-15').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-14').toISOString(),
        },
        {
            orderId: 'PO-2024-018',
            stage: 'Polishing',
            progress: 75,
            assignedEmployee: null,
            startDate: new Date('2024-02-18').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-17').toISOString(),
        },
        {
            orderId: 'PO-2024-019',
            stage: 'Packaging',
            progress: 60,
            assignedEmployee: 'Sofia Rossi',
            startDate: new Date('2024-02-20').toISOString(),
            endDate: null,
            status: 'In Progress',
            createdAt: new Date('2024-02-19').toISOString(),
        },
        {
            orderId: 'PO-2024-020',
            stage: 'Delivery',
            progress: 100,
            assignedEmployee: 'Thomas Mueller',
            startDate: new Date('2024-02-22').toISOString(),
            endDate: new Date('2024-03-03').toISOString(),
            status: 'Completed',
            createdAt: new Date('2024-02-21').toISOString(),
        },
    ];

    await db.insert(productionOrders).values(sampleProductionOrders);
    
    console.log('✅ Production orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});