import { db } from '@/db';
import { projects } from '@/db/schema';

async function main() {
    const sampleProjects = [
        {
            name: 'Grand Hyatt Hotel Lobby Renovation',
            clientId: 3,
            budget: 18500000,
            dueDate: new Date('2024-12-15').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Mediterranean Villa Marble Flooring',
            clientId: 7,
            budget: 12750000,
            dueDate: new Date('2025-03-20').toISOString(),
            status: 'ongoing',
            progress: 65,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Corporate Headquarters Main Entrance',
            clientId: 1,
            budget: 9500000,
            dueDate: new Date('2024-11-30').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Luxury Spa Center Interior Design',
            clientId: 12,
            budget: 15200000,
            dueDate: new Date('2025-04-15').toISOString(),
            status: 'ongoing',
            progress: 45,
            createdAt: new Date('2024-04-20').toISOString(),
        },
        {
            name: 'Shopping Mall Central Atrium',
            clientId: 5,
            budget: 20000000,
            dueDate: new Date('2025-06-30').toISOString(),
            status: 'ongoing',
            progress: 30,
            createdAt: new Date('2024-05-10').toISOString(),
        },
        {
            name: 'Fine Dining Restaurant Kitchen & Bar',
            clientId: 9,
            budget: 6800000,
            dueDate: new Date('2024-10-15').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-06-01').toISOString(),
        },
        {
            name: 'Penthouse Suite Bathroom Renovation',
            clientId: 14,
            budget: 4500000,
            dueDate: new Date('2025-02-28').toISOString(),
            status: 'ongoing',
            progress: 70,
            createdAt: new Date('2024-07-15').toISOString(),
        },
        {
            name: 'Museum Exhibition Hall Flooring',
            clientId: 2,
            budget: 11300000,
            dueDate: new Date('2024-09-20').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-08-01').toISOString(),
        },
        {
            name: 'Boutique Hotel Reception Area',
            clientId: 8,
            budget: 7200000,
            dueDate: new Date('2025-05-10').toISOString(),
            status: 'ongoing',
            progress: 55,
            createdAt: new Date('2024-08-20').toISOString(),
        },
        {
            name: 'Executive Office Tower Elevators',
            clientId: 4,
            budget: 13600000,
            dueDate: new Date('2025-07-15').toISOString(),
            status: 'ongoing',
            progress: 40,
            createdAt: new Date('2024-09-05').toISOString(),
        },
        {
            name: 'Private Residence Master Staircase',
            clientId: 11,
            budget: 8900000,
            dueDate: new Date('2024-12-30').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-09-20').toISOString(),
        },
        {
            name: 'Casino Main Gaming Floor',
            clientId: 6,
            budget: 17800000,
            dueDate: new Date('2025-08-20').toISOString(),
            status: 'ongoing',
            progress: 35,
            createdAt: new Date('2024-10-10').toISOString(),
        },
        {
            name: 'Wellness Center Sauna & Steam Room',
            clientId: 15,
            budget: 5400000,
            dueDate: new Date('2025-01-30').toISOString(),
            status: 'ongoing',
            progress: 80,
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            name: 'Airport VIP Lounge Renovation',
            clientId: 10,
            budget: 14200000,
            dueDate: new Date('2024-11-15').toISOString(),
            status: 'completed',
            progress: 100,
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            name: 'Theater Foyer & Concourse',
            clientId: 3,
            budget: 10500000,
            dueDate: new Date('2025-09-30').toISOString(),
            status: 'pending',
            progress: 5,
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            name: 'Country Club Clubhouse Interior',
            clientId: 13,
            budget: 12100000,
            dueDate: new Date('2024-08-30').toISOString(),
            status: 'cancelled',
            progress: 25,
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'Bank Branch Marble Facade',
            clientId: 7,
            budget: 9800000,
            dueDate: new Date('2025-10-15').toISOString(),
            status: 'pending',
            progress: 0,
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Rooftop Terrace Marble Installation',
            clientId: 1,
            budget: 6200000,
            dueDate: new Date('2025-11-20').toISOString(),
            status: 'pending',
            progress: 10,
            createdAt: new Date('2024-12-20').toISOString(),
        },
        {
            name: 'Convention Center Main Hall',
            clientId: 9,
            budget: 19500000,
            dueDate: new Date('2024-07-15').toISOString(),
            status: 'cancelled',
            progress: 40,
            createdAt: new Date('2025-01-05').toISOString(),
        },
        {
            name: 'Yacht Club Marina Pavilion',
            clientId: 5,
            budget: 3000000,
            dueDate: new Date('2025-12-30').toISOString(),
            status: 'pending',
            progress: 15,
            createdAt: new Date('2025-01-15').toISOString(),
        },
    ];

    await db.insert(projects).values(sampleProjects);
    
    console.log('✅ Projects seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});